image: docker:git
services:
- docker:dind

stages:
  - build
  - push

variables:
  RELEASE_NAME: docker-git-ssh-minimal

build:
  stage: build
  script:
    - docker build -t $RELEASE_NAME:${CI_COMMIT_SHORT_SHA} .

push_latest:
  stage: push
  only:
    - main
  script:
    - docker rm $RELEASE_NAME-latest || echo kein alter container
    - docker rmi $RELEASE_NAME-latest || echo kein altes image
    - docker tag $RELEASE_NAME:${CI_COMMIT_SHORT_SHA} $RELEASE_NAME:latest
    - docker create -it --name=$RELEASE_NAME-latest $RELEASE_NAME:latest

push_tag:
  stage: push
  only:
    - tags
  script:
    - docker rm $RELEASE_NAME-${CI_COMMIT_TAG} || echo kein alter container
    - docker rmi $RELEASE_NAME-${CI_COMMIT_TAG} || echo kein altes image
    - docker tag $RELEASE_NAME:${CI_COMMIT_SHORT_SHA} $RELEASE_NAME:${CI_COMMIT_TAG}
    - docker create -it --name=$RELEASE_NAME-${CI_COMMIT_TAG} $RELEASE_NAME:${CI_COMMIT_TAG}


